import { existsSync, mkdirSync, readFileSync, watch, writeFileSync } from "node:fs";
import path from "node:path";
import { parseSchemaFile } from "../schema-file/format";
import type { SchemaFile } from "../schema-file/types";

/** Where a site keeps its schema file, in the order `monti` looks for it. */
export const SCHEMA_FILE_CANDIDATES = ["monti.schema.json", "src/monti.schema.json"] as const;
/** Link to the JSON Schema the package ships, relative to a schema file at the site root. */
export const SCHEMA_LINK = "./node_modules/@monti-cms/core/schema.json";
/** Default name of the generated declaration file, next to the schema file. */
export const SCHEMA_TYPES_FILE = "monti-env.d.ts";

const IDENTIFIER = /^[A-Za-z_$][\w$]*$/;

/** Prints a JSON value as a TypeScript literal type: every property `readonly`, every array a `readonly` tuple, every string its own literal type. */
export function toTypeLiteral(value: unknown, depth = 0): string {
	if (value === null) return "null";
	if (typeof value === "string") return JSON.stringify(value);
	if (typeof value === "number" || typeof value === "boolean") return String(value);
	const pad = "\t".repeat(depth + 1);
	const end = "\t".repeat(depth);
	if (Array.isArray(value)) {
		if (value.length === 0) return "readonly []";
		return `readonly [\n${value.map((item) => `${pad}${toTypeLiteral(item, depth + 1)},`).join("\n")}\n${end}]`;
	}
	if (typeof value === "object") {
		const entries = Object.entries(value).filter(([, item]) => item !== undefined);
		if (entries.length === 0) return "{}";
		return `{\n${entries
			.map(
				([key, item]) =>
					`${pad}readonly ${IDENTIFIER.test(key) ? key : JSON.stringify(key)}: ${toTypeLiteral(item, depth + 1)};`,
			)
			.join("\n")}\n${end}}`;
	}
	throw new Error(`cannot write ${typeof value} as a type`);
}

/**
 * The declaration file for a schema: it registers the file's collections, locales and default locale in `MontiRegister`, so `defineSite({ schema })`,
 * `createCms`, `cms.read` and `DocumentComponentsFor` know the site's collection names, the shape of each collection's metadata, and the locale codes,
 * with nothing written by hand. It holds types only: nothing is imported at run time.
 */
export function schemaTypesText(file: SchemaFile, schemaName = "monti.schema.json"): string {
	const types = { collections: file.collections, locales: file.locales, defaultLocale: file.defaultLocale };
	const body = toTypeLiteral(types, 2);
	return `// Generated by \`monti schema:types\` from ${schemaName}. Do not edit: it is rewritten when the schema changes.
import "@monti-cms/core";

declare module "@monti-cms/core" {
	interface MontiRegister {
		schema: ${body};
	}
}
`;
}

export interface SchemaTypesOptions {
	readonly cwd: string;
	/** Schema file (relative to `cwd`). Default: `monti.schema.json`, then `src/monti.schema.json`. */
	readonly schema?: string;
	/** Declaration file to write (relative to `cwd`). Default: `monti-env.d.ts` next to the schema file. */
	readonly out?: string;
	/** Write nothing; report whether the declaration file is up to date. */
	readonly check?: boolean;
	readonly log?: (message: string) => void;
}

export interface SchemaTypesResult {
	/** Schema file, relative to `cwd`. */
	readonly schema: string;
	/** Declaration file, relative to `cwd`. */
	readonly out: string;
	/** Whether the declaration file was (or, with `check`, would be) changed. */
	readonly changed: boolean;
}

const posix = (file: string) => file.split(path.sep).join("/");

/** The schema file of a site: the chosen path, or the first default location that exists. Throws if there is none. */
export function findSchemaFile(cwd: string, chosen?: string): string {
	const found = chosen ?? SCHEMA_FILE_CANDIDATES.find((candidate) => existsSync(path.join(cwd, candidate)));
	if (!found || !existsSync(path.resolve(cwd, found))) {
		throw new Error(
			found
				? `schema file not found: ${found}`
				: `cannot find ${SCHEMA_FILE_CANDIDATES[0]}; pass --schema <path> (\`monti init\` creates one, \`monti schema:extract\` makes one from cms.config.ts)`,
		);
	}
	return found;
}

/** Reads and checks a schema file. Errors name the file and the JSON path of each problem. */
export function readSchema(cwd: string, schema: string): SchemaFile {
	const text = readFileSync(path.resolve(cwd, schema), "utf8");
	let json: unknown;
	try {
		json = JSON.parse(text);
	} catch (error) {
		throw new Error(`${schema} is not valid JSON: ${(error as Error).message}`);
	}
	return parseSchemaFile(json, schema);
}

/** Writes a file only when its content differs. Returns whether it changed. */
function writeIfChanged(file: string, content: string, check: boolean): boolean {
	const current = existsSync(file) ? readFileSync(file, "utf8") : undefined;
	if (current === content) return false;
	if (!check) {
		mkdirSync(path.dirname(file), { recursive: true });
		writeFileSync(file, content);
	}
	return true;
}

/** `monti schema:types`: reads the schema file and writes the declaration file. With `check`, writes nothing and tells whether the file is out of date. */
export function generateSchemaTypes(options: SchemaTypesOptions): SchemaTypesResult {
	const schema = findSchemaFile(options.cwd, options.schema);
	const out = options.out ?? posix(path.join(path.dirname(schema), SCHEMA_TYPES_FILE));
	const file = readSchema(options.cwd, schema);
	const name = posix(path.relative(path.dirname(out), schema)) || schema;
	const changed = writeIfChanged(path.resolve(options.cwd, out), schemaTypesText(file, name), options.check ?? false);
	return { schema, out, changed };
}

/**
 * Writes the declaration file now and again every time the schema file changes, until the returned function is called. A schema that is half written or invalid
 * is reported through `log` and the last good declaration file stays. Used by `monti schema:types --watch` and by `withCms` in the dev server.
 */
export function watchSchemaTypes(
	options: SchemaTypesOptions & {
		readonly debounceMs?: number;
		/** Whether the watch keeps the process alive. Default true (the command); a dev server that only wants the types kept fresh passes false. */
		readonly persistent?: boolean;
	},
): () => void {
	const log = options.log ?? console.log;
	const schema = findSchemaFile(options.cwd, options.schema);
	const run = () => {
		try {
			const result = generateSchemaTypes({ ...options, schema });
			if (result.changed) log(`monti: wrote ${result.out} from ${result.schema}`);
		} catch (error) {
			log(`monti: ${error instanceof Error ? error.message : String(error)}`);
		}
	};
	run();
	let timer: ReturnType<typeof setTimeout> | undefined;
	// Watch the folder: editors that save by replacing the file would end a watch on the file itself.
	const dir = path.dirname(path.resolve(options.cwd, schema));
	const base = path.basename(schema);
	const watcher = watch(dir, { persistent: options.persistent ?? true }, (_event, name) => {
		if (name && name !== base) return;
		clearTimeout(timer);
		timer = setTimeout(run, options.debounceMs ?? 100);
	});
	return () => {
		clearTimeout(timer);
		watcher.close();
	};
}
