// Generated by `monti schema:types` from monti.schema.json. Do not edit: it is rewritten when the schema changes.
import "@monti-cms/core";

declare module "@monti-cms/core" {
	interface MontiRegister {
		schema: {
			readonly collections: {
				readonly post: {
					readonly label: "Post";
					readonly kind: "document";
					readonly fields: {
						readonly title: {
							readonly kind: "text";
							readonly label: "Title";
							readonly required: true;
							readonly localized: true;
							readonly max: 200;
							readonly placeholder: "Untitled post";
						};
						readonly slug: {
							readonly kind: "slug";
							readonly label: "Address";
							readonly description: "Changing the address of a published entry sends the old address to the new one with a 308 redirect.";
							readonly required: true;
							readonly localized: "inherit";
							readonly from: "title";
							readonly placeholder: "url-friendly-slug";
						};
						readonly summary: {
							readonly kind: "text";
							readonly label: "Summary";
							readonly localized: true;
							readonly role: "summary";
							readonly fillFromBody: true;
							readonly multiline: true;
							readonly rows: 3;
							readonly placeholder: "Intro shown in lists and search results";
						};
						readonly categoryId: {
							readonly kind: "relation";
							readonly label: "Category";
							readonly required: true;
							readonly to: "category";
							readonly createInline: true;
						};
						readonly tagIds: {
							readonly kind: "relation";
							readonly label: "Tags";
							readonly description: "Keeps the order you pick them in.";
							readonly to: "tag";
							readonly many: true;
							readonly createInline: true;
						};
						readonly series: {
							readonly kind: "backlink";
							readonly label: "Series";
							readonly description: "Saved to the series at once, apart from the draft and publish state of the post. A new post goes to the end of the series.";
							readonly from: "collection";
							readonly via: "itemIds";
							readonly createInline: true;
							readonly placeholder: "Add to a series";
						};
						readonly policy: {
							readonly kind: "conditional";
							readonly label: "Policy";
							readonly description: "A deprecated post points readers to its replacement.";
							readonly discriminant: {
								readonly kind: "select";
								readonly label: "Policy";
								readonly description: "A deprecated post points readers to its replacement.";
								readonly options: {
									readonly normal: "Normal";
									readonly evergreen: "Always current";
									readonly deprecated: "Deprecated";
								};
								readonly defaultValue: "normal";
							};
							readonly values: {
								readonly deprecated: {
									readonly replacementPostId: {
										readonly kind: "relation";
										readonly label: "Replacement post";
										readonly to: "post";
										readonly publishedOnly: true;
										readonly placeholder: "Pick a published post";
									};
								};
							};
						};
						readonly recordStatus: {
							readonly kind: "select";
							readonly label: "Work status";
							readonly description: "Set by hand, apart from whether the entry is published.";
							readonly options: {
								readonly unspecified: "Not specified";
								readonly experimental: "Experimenting";
								readonly verified: "Verified";
								readonly maintained: "Maintained";
								readonly stale: "Needs review";
							};
							readonly defaultValue: "unspecified";
						};
						readonly recordObservation: {
							readonly kind: "text";
							readonly label: "Observation / question";
							readonly localized: true;
							readonly multiline: true;
							readonly rows: 3;
						};
						readonly recordExperiment: {
							readonly kind: "text";
							readonly label: "Attempt / experiment";
							readonly localized: true;
							readonly multiline: true;
							readonly rows: 3;
						};
						readonly recordResult: {
							readonly kind: "text";
							readonly label: "Result / open question";
							readonly localized: true;
							readonly multiline: true;
							readonly rows: 3;
						};
						readonly relatedPostIds: {
							readonly kind: "relation";
							readonly label: "Follow-up posts";
							readonly to: "post";
							readonly many: true;
							readonly publishedOnly: true;
						};
						readonly relatedMemoIds: {
							readonly kind: "relation";
							readonly label: "Follow-up memos";
							readonly to: "memo";
							readonly many: true;
							readonly publishedOnly: true;
						};
						readonly searchPreview: {
							readonly kind: "view";
							readonly view: "search";
							readonly tab: "SEO";
						};
						readonly seoTitle: {
							readonly kind: "text";
							readonly label: "Search title";
							readonly localized: true;
							readonly input: "seo-title";
							readonly inputOptions: {
								readonly limit: 60;
							};
							readonly role: "seoTitle";
							readonly tab: "SEO";
						};
						readonly seoDescription: {
							readonly kind: "text";
							readonly label: "Search description";
							readonly localized: true;
							readonly input: "seo-description";
							readonly inputOptions: {
								readonly limit: 155;
							};
							readonly role: "seoDescription";
							readonly tab: "SEO";
							readonly multiline: true;
						};
						readonly ogImageId: {
							readonly kind: "media";
							readonly label: "Share image";
							readonly localized: true;
							readonly role: "ogImage";
							readonly tab: "SEO";
							readonly accept: "image";
						};
						readonly seoRobots: {
							readonly kind: "select";
							readonly label: "Hide from search engines";
							readonly input: "seo-noindex";
							readonly role: "noindex";
							readonly tab: "SEO";
							readonly options: {
								readonly index: "Show";
								readonly noindex: "Hide";
							};
							readonly defaultValue: "index";
						};
						readonly canonicalUrl: {
							readonly kind: "text";
							readonly label: "Original URL";
							readonly localized: true;
							readonly role: "canonical";
							readonly tab: "SEO";
							readonly placeholder: "https://";
						};
					};
					readonly path: "/posts/:slug";
					readonly icon: "file-text";
					readonly layout: readonly [
						{
							readonly fields: readonly [
								"title",
								"slug",
								"summary",
							];
						},
						{
							readonly group: "Classification";
							readonly fields: readonly [
								"categoryId",
								"tagIds",
								"series",
							];
						},
						{
							readonly group: "Policy";
							readonly fields: readonly [
								"policy",
							];
						},
						{
							readonly group: "Work log";
							readonly fields: readonly [
								"recordStatus",
								"recordObservation",
								"recordExperiment",
								"recordResult",
								"relatedPostIds",
								"relatedMemoIds",
							];
						},
					];
				};
				readonly memo: {
					readonly label: "Memo";
					readonly kind: "document";
					readonly fields: {
						readonly title: {
							readonly kind: "text";
							readonly label: "Title";
							readonly required: true;
							readonly localized: true;
							readonly max: 200;
							readonly placeholder: "Untitled post";
						};
						readonly slug: {
							readonly kind: "slug";
							readonly label: "Address";
							readonly description: "Changing the address of a published entry sends the old address to the new one with a 308 redirect.";
							readonly required: true;
							readonly localized: "inherit";
							readonly from: "title";
							readonly placeholder: "url-friendly-slug";
						};
						readonly tagIds: {
							readonly kind: "relation";
							readonly label: "Tags";
							readonly description: "Keeps the order you pick them in.";
							readonly to: "tag";
							readonly many: true;
							readonly createInline: true;
						};
						readonly series: {
							readonly kind: "backlink";
							readonly label: "Series";
							readonly description: "Saved to the series at once, apart from the draft and publish state of the memo. Only series that hold memos can be picked, and a new memo goes to the end.";
							readonly from: "collection";
							readonly via: "memoIds";
							readonly createInline: true;
							readonly placeholder: "Add to a series";
						};
						readonly recordStatus: {
							readonly kind: "select";
							readonly label: "Work status";
							readonly description: "Set by hand, apart from whether the entry is published.";
							readonly options: {
								readonly unspecified: "Not specified";
								readonly experimental: "Experimenting";
								readonly verified: "Verified";
								readonly maintained: "Maintained";
								readonly stale: "Needs review";
							};
							readonly defaultValue: "unspecified";
						};
						readonly recordObservation: {
							readonly kind: "text";
							readonly label: "Observation / question";
							readonly localized: true;
							readonly multiline: true;
							readonly rows: 3;
						};
						readonly recordExperiment: {
							readonly kind: "text";
							readonly label: "Attempt / experiment";
							readonly localized: true;
							readonly multiline: true;
							readonly rows: 3;
						};
						readonly recordResult: {
							readonly kind: "text";
							readonly label: "Result / open question";
							readonly localized: true;
							readonly multiline: true;
							readonly rows: 3;
						};
						readonly relatedPostIds: {
							readonly kind: "relation";
							readonly label: "Follow-up posts";
							readonly to: "post";
							readonly many: true;
							readonly publishedOnly: true;
						};
						readonly relatedMemoIds: {
							readonly kind: "relation";
							readonly label: "Follow-up memos";
							readonly to: "memo";
							readonly many: true;
							readonly publishedOnly: true;
						};
						readonly searchPreview: {
							readonly kind: "view";
							readonly view: "search";
							readonly tab: "SEO";
						};
						readonly seoTitle: {
							readonly kind: "text";
							readonly label: "Search title";
							readonly localized: true;
							readonly input: "seo-title";
							readonly inputOptions: {
								readonly limit: 60;
							};
							readonly role: "seoTitle";
							readonly tab: "SEO";
						};
						readonly seoDescription: {
							readonly kind: "text";
							readonly label: "Search description";
							readonly localized: true;
							readonly input: "seo-description";
							readonly inputOptions: {
								readonly limit: 155;
							};
							readonly role: "seoDescription";
							readonly tab: "SEO";
							readonly multiline: true;
						};
						readonly ogImageId: {
							readonly kind: "media";
							readonly label: "Share image";
							readonly localized: true;
							readonly role: "ogImage";
							readonly tab: "SEO";
							readonly accept: "image";
						};
						readonly seoRobots: {
							readonly kind: "select";
							readonly label: "Hide from search engines";
							readonly input: "seo-noindex";
							readonly role: "noindex";
							readonly tab: "SEO";
							readonly options: {
								readonly index: "Show";
								readonly noindex: "Hide";
							};
							readonly defaultValue: "index";
						};
						readonly canonicalUrl: {
							readonly kind: "text";
							readonly label: "Original URL";
							readonly localized: true;
							readonly role: "canonical";
							readonly tab: "SEO";
							readonly placeholder: "https://";
						};
					};
					readonly path: "/memos/:slug";
					readonly icon: "notebook-pen";
					readonly layout: readonly [
						{
							readonly fields: readonly [
								"title",
								"slug",
							];
						},
						{
							readonly group: "Classification";
							readonly fields: readonly [
								"tagIds",
								"series",
							];
						},
						{
							readonly group: "Work log";
							readonly fields: readonly [
								"recordStatus",
								"recordObservation",
								"recordExperiment",
								"recordResult",
								"relatedPostIds",
								"relatedMemoIds",
							];
						},
					];
				};
				readonly category: {
					readonly label: "Category";
					readonly kind: "item";
					readonly fields: {
						readonly title: {
							readonly kind: "text";
							readonly label: "Name";
							readonly required: true;
							readonly localized: true;
							readonly max: 200;
						};
						readonly slug: {
							readonly kind: "slug";
							readonly label: "Address";
							readonly required: true;
							readonly from: "title";
						};
					};
					readonly icon: "shapes";
				};
				readonly tag: {
					readonly label: "Tag";
					readonly kind: "item";
					readonly fields: {
						readonly title: {
							readonly kind: "text";
							readonly label: "Name";
							readonly required: true;
							readonly localized: true;
							readonly max: 200;
						};
						readonly slug: {
							readonly kind: "slug";
							readonly label: "Address";
							readonly required: true;
							readonly from: "title";
						};
					};
					readonly icon: "tag";
				};
				readonly collection: {
					readonly label: "Series";
					readonly kind: "item";
					readonly fields: {
						readonly title: {
							readonly kind: "text";
							readonly label: "Name";
							readonly required: true;
							readonly localized: true;
							readonly max: 200;
						};
						readonly slug: {
							readonly kind: "slug";
							readonly label: "Address";
							readonly required: true;
							readonly from: "title";
						};
						readonly summary: {
							readonly kind: "text";
							readonly label: "Description";
							readonly localized: true;
							readonly role: "summary";
							readonly multiline: true;
						};
						readonly itemKind: {
							readonly kind: "conditional";
							readonly label: "Holds";
							readonly description: "Saving with another kind empties the list of the other kind.";
							readonly discriminant: {
								readonly kind: "select";
								readonly label: "Holds";
								readonly description: "Saving with another kind empties the list of the other kind.";
								readonly options: {
									readonly post: "Posts";
									readonly memo: "Memos";
								};
								readonly defaultValue: "post";
							};
							readonly values: {
								readonly post: {
									readonly itemIds: {
										readonly kind: "relation";
										readonly label: "Posts";
										readonly description: "Unpublished posts can be added too; they only stay out of the public list.";
										readonly to: "post";
										readonly many: true;
										readonly allowUnpublished: true;
										readonly ordered: true;
										readonly placeholder: "Add or remove posts";
									};
								};
								readonly memo: {
									readonly memoIds: {
										readonly kind: "relation";
										readonly label: "Memos";
										readonly description: "Unpublished memos can be added too; they only stay out of the public list.";
										readonly to: "memo";
										readonly many: true;
										readonly allowUnpublished: true;
										readonly ordered: true;
										readonly placeholder: "Add or remove memos";
									};
								};
							};
						};
					};
					readonly icon: "layers";
				};
			};
			readonly locales: readonly [
				{
					readonly code: "ko";
					readonly name: "한국어";
					readonly label: "Korean";
				},
				{
					readonly code: "en";
					readonly name: "English";
					readonly label: "English";
				},
			];
			readonly defaultLocale: "ko";
		};
	}
}
