import { execFileSync } from "node:child_process";
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { blogSchema, cloneSchema } from "../../schema-file/__test__/fixture";
import { runCli } from "..";
import { generateSchemaTypes, schemaTypesText, toTypeLiteral, watchSchemaTypes } from "../schema-types";

const PACKAGE = path.resolve(import.meta.dirname, "../../..");

let dirs: string[] = [];
afterEach(() => {
	for (const dir of dirs) rmSync(dir, { recursive: true, force: true });
	dirs = [];
});
const tempDir = (parent = tmpdir()) => {
	const dir = mkdtempSync(path.join(parent, "monti-types-"));
	dirs.push(dir);
	return dir;
};
const write = (dir: string, file: string, content: unknown) => {
	mkdirSync(path.dirname(path.join(dir, file)), { recursive: true });
	writeFileSync(
		path.join(dir, file),
		typeof content === "string" ? content : `${JSON.stringify(content, null, "\t")}\n`,
	);
};
const read = (dir: string, file: string) => readFileSync(path.join(dir, file), "utf8");

describe("toTypeLiteral", () => {
	it("prints JSON as readonly literal types", () => {
		expect(toTypeLiteral({ a: "x", "b-c": [1, true, null], d: {}, e: [] })).toBe(
			'{\n\treadonly a: "x";\n\treadonly "b-c": readonly [\n\t\t1,\n\t\ttrue,\n\t\tnull,\n\t];\n\treadonly d: {};\n\treadonly e: readonly [];\n}',
		);
	});

	it("keeps a string with quotes and line breaks as one literal", () => {
		const literal = toTypeLiteral('He said "hi"\nbye');
		expect(literal).toBe('"He said \\"hi\\"\\nbye"');
		expect(JSON.parse(literal)).toBe('He said "hi"\nbye');
	});
});

describe("monti schema:types", () => {
	it("registers collections, locales and the default locale, and nothing else", () => {
		const text = schemaTypesText(blogSchema as never);
		expect(text).toContain("Generated by `monti schema:types` from monti.schema.json");
		expect(text).toContain('import "@monti-cms/core";');
		expect(text).toContain('declare module "@monti-cms/core"');
		expect(text).toContain("interface MontiRegister");
		expect(text).toContain('readonly path: "/posts/:slug";');
		expect(text).toContain('readonly defaultLocale: "ko";');
		expect(text).not.toContain("seed");
		expect(text).not.toContain("Ship it");
	});

	it("writes next to the schema file, leaves an up-to-date file alone, and notices a change", () => {
		const dir = tempDir();
		write(dir, "monti.schema.json", blogSchema);
		const first = generateSchemaTypes({ cwd: dir });
		expect(first).toEqual({ schema: "monti.schema.json", out: "monti-env.d.ts", changed: true });
		expect(read(dir, "monti-env.d.ts")).toContain('readonly defaultLocale: "ko";');
		expect(generateSchemaTypes({ cwd: dir }).changed).toBe(false);

		const edited = cloneSchema();
		edited.defaultLocale = "en";
		write(dir, "monti.schema.json", edited);
		expect(generateSchemaTypes({ cwd: dir, check: true }).changed).toBe(true);
		// `check` writes nothing.
		expect(read(dir, "monti-env.d.ts")).toContain('readonly defaultLocale: "ko";');
		expect(generateSchemaTypes({ cwd: dir }).changed).toBe(true);
		expect(read(dir, "monti-env.d.ts")).toContain('readonly defaultLocale: "en";');
	});

	it("finds the schema in src/, and takes a chosen schema and output path", () => {
		const dir = tempDir();
		write(dir, "src/monti.schema.json", blogSchema);
		expect(generateSchemaTypes({ cwd: dir })).toMatchObject({
			schema: "src/monti.schema.json",
			out: "src/monti-env.d.ts",
		});
		write(dir, "config/site.schema.json", blogSchema);
		expect(generateSchemaTypes({ cwd: dir, schema: "config/site.schema.json", out: "types/monti.d.ts" })).toMatchObject(
			{
				out: "types/monti.d.ts",
			},
		);
		expect(read(dir, "types/monti.d.ts")).toContain("from ../config/site.schema.json");
	});

	it("names the file and the JSON path when the schema is invalid, and writes nothing", () => {
		const dir = tempDir();
		const broken = cloneSchema();
		broken.collections.post.fields.title.kind = "date";
		write(dir, "monti.schema.json", broken);
		expect(() => generateSchemaTypes({ cwd: dir })).toThrow(
			/monti\.schema\.json is not a valid schema file[\s\S]*collections\.post\.fields\.title\.kind/,
		);
		write(dir, "monti.schema.json", "{ nope");
		expect(() => generateSchemaTypes({ cwd: dir })).toThrow(/monti\.schema\.json is not valid JSON/);
		expect(() => read(dir, "monti-env.d.ts")).toThrow();
	});

	it("says how to get a schema file when there is none", () => {
		expect(() => generateSchemaTypes({ cwd: tempDir() })).toThrow(/cannot find monti\.schema\.json; pass --schema/);
		expect(() => generateSchemaTypes({ cwd: tempDir(), schema: "x.json" })).toThrow(/schema file not found: x\.json/);
	});

	it("is a command, and `--check` fails (exit 1) while the types are out of date", async () => {
		const dir = tempDir();
		write(dir, "monti.schema.json", blogSchema);
		const run = async (...args: string[]) => {
			const out: string[] = [];
			const err: string[] = [];
			const code = await runCli(args, { cwd: dir, log: (line) => out.push(line), error: (line) => err.push(line) });
			return { code, out: out.join("\n"), err: err.join("\n") };
		};
		expect((await run("schema:types", "--check")).code).toBe(1);
		expect(await run("schema:types")).toMatchObject({ code: 0, out: "Wrote monti-env.d.ts from monti.schema.json" });
		expect((await run("schema:types", "--check")).code).toBe(0);
		expect(await run("schema:types")).toMatchObject({ code: 0, out: "monti-env.d.ts is up to date" });
		write(dir, "monti.schema.json", "{ nope");
		const failed = await run("schema:types");
		expect(failed.code).toBe(1);
		expect(failed.err).toContain("is not valid JSON");
	});

	it("rewrites the types when the schema file changes while watching, and keeps the last good ones for a broken save", async () => {
		const dir = tempDir();
		write(dir, "monti.schema.json", blogSchema);
		const messages: string[] = [];
		const stop = watchSchemaTypes({ cwd: dir, debounceMs: 10, log: (message) => messages.push(message) });
		try {
			expect(read(dir, "monti-env.d.ts")).toContain('readonly defaultLocale: "ko";');
			// The file system's change notifications can miss a change made the moment the watch starts.
			await new Promise((resolve) => setTimeout(resolve, 300));
			const until = async (check: () => boolean) => {
				for (let attempt = 0; attempt < 100 && !check(); attempt++)
					await new Promise((resolve) => setTimeout(resolve, 50));
				expect(check(), messages.join("\n")).toBe(true);
			};
			const edited = cloneSchema();
			edited.defaultLocale = "en";
			write(dir, "monti.schema.json", edited);
			await until(() => read(dir, "monti-env.d.ts").includes('readonly defaultLocale: "en";'));
			write(dir, "monti.schema.json", "{ half written");
			await until(() => messages.some((message) => message.includes("is not valid JSON")));
			expect(read(dir, "monti-env.d.ts")).toContain('readonly defaultLocale: "en";');
		} finally {
			stop();
		}
	});
});

/** The types as the site's TypeScript sees them: a project with the schema, the generated file and a config that imports the JSON. */
describe("typing from the generated file", () => {
	const TSC = path.join(PACKAGE, "node_modules/.bin/tsc");

	/** Writes a project inside the package (so `@types/node` and zod resolve), generates the types if asked, and runs the type checker on `check.ts`. */
	function typecheck(options: { generated: boolean; check: string }): { ok: boolean; output: string } {
		const dir = tempDir(PACKAGE);
		write(dir, "monti.schema.json", blogSchema);
		write(
			dir,
			"cms.config.ts",
			`import { defineSite } from "@monti-cms/core";\nimport schema from "./monti.schema.json";\n\nexport default defineSite({ schema });\n`,
		);
		write(dir, "check.ts", options.check);
		write(dir, "tsconfig.json", {
			compilerOptions: {
				target: "ES2022",
				lib: ["dom", "esnext"],
				strict: true,
				noEmit: true,
				module: "esnext",
				moduleResolution: "bundler",
				resolveJsonModule: true,
				skipLibCheck: true,
				jsx: "react-jsx",
				types: ["node"],
				paths: {
					"@monti-cms/core": ["../src/index.ts"],
					"@monti-cms/core/server": ["../src/server/index.ts"],
					"@monti-cms/core/render": ["../src/render/index.tsx"],
				},
			},
			include: ["*.ts", "*.d.ts"],
		});
		if (options.generated) generateSchemaTypes({ cwd: dir });
		try {
			execFileSync(TSC, ["-p", dir], { cwd: dir, encoding: "utf8", stdio: "pipe" });
			return { ok: true, output: "" };
		} catch (error) {
			const failure = error as { stdout?: string; stderr?: string };
			return { ok: false, output: `${failure.stdout ?? ""}${failure.stderr ?? ""}` };
		}
	}

	const CHECK = `
import type { Cms } from "@monti-cms/core/server";
import type { DocumentComponentsFor } from "@monti-cms/core/render";
import type { CollectionName, MetadataFor } from "../src/core/types";
import config from "./cms.config";

type Equal<A, B> = (<T>() => T extends A ? 1 : 2) extends <T>() => T extends B ? 1 : 2 ? true : false;
type Post = MetadataFor<"post", typeof config>;

export const names: Equal<CollectionName<typeof config>, "post" | "category" | "tag" | "series"> = true;
export const locale: Equal<typeof config["defaultLocale"], "ko" | "en"> = true;
export const select: Equal<NonNullable<Post["policy"]>, "normal" | "deprecated"> = true;
export const many: Equal<NonNullable<Post["tagIds"]>, readonly string[]> = true;
export const dependent: Equal<NonNullable<Post["replacementId"]>, string> = true;
export const noCollection: Equal<MetadataFor<"nope", typeof config>, never> = true;

declare const cms: Cms<typeof config>;
export const read = cms.read.getEntry({ collection: "post", slug: "a" });
// @ts-expect-error not a collection of the schema
export const unknownCollection = cms.read.getEntry({ collection: "page", slug: "a" });
export const components = {} satisfies DocumentComponentsFor<typeof config>;
`;

	it("gives createCms, cms.read, MetadataFor and DocumentComponentsFor the schema's names and shapes, with nothing written by hand", () => {
		const result = typecheck({ generated: true, check: CHECK });
		expect(result.output).toBe("");
		expect(result.ok).toBe(true);
	}, 120_000);

	it("is checked: the same assertions fail without the generated file, where names are plain strings", () => {
		const result = typecheck({ generated: false, check: CHECK });
		expect(result.ok).toBe(false);
		expect(result.output).toContain("Type 'true' is not assignable to type 'false'");
	}, 120_000);
});
