#!/usr/bin/env node
/**
 * Creates the release bundle folder. Packs the built packages with `pnpm pack` (`publishConfig` and `workspace:*` versions are applied),
 * unpacks them into `<output folder>/<package folder name>/`. The release workflow pushes this folder to the `release` branch.
 *
 *   pnpm build && node scripts/pack-release.mjs <output folder>
 *
 * Until the public release, install from the GitHub address instead of npm:
 *   "@monti-cms/core": "github:monti-cms/monti#release/v0.1.0&path:/core"
 */
import { execFileSync } from "node:child_process";
import {
	copyFileSync,
	mkdirSync,
	mkdtempSync,
	readdirSync,
	readFileSync,
	renameSync,
	rmSync,
	writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const out = process.argv[2] && path.resolve(process.argv[2]);
if (!out) {
	console.error("Usage: node scripts/pack-release.mjs <out-dir>");
	process.exit(1);
}

const packages = readdirSync(path.join(root, "packages"), { withFileTypes: true })
	.filter((entry) => entry.isDirectory())
	.map((entry) => {
		const dir = path.join(root, "packages", entry.name);
		return { dir, folder: entry.name, pkg: JSON.parse(readFileSync(path.join(dir, "package.json"), "utf8")) };
	});

// Packages are always released with the same version (`scripts/version.mjs`).
const versions = new Set(packages.map(({ pkg }) => pkg.version));
if (versions.size !== 1) {
	console.error(`Package versions differ: ${[...versions].join(", ")}. Run scripts/version.mjs first.`);
	process.exit(1);
}
const [version] = versions;

rmSync(out, { recursive: true, force: true });
mkdirSync(out, { recursive: true });
const work = mkdtempSync(path.join(tmpdir(), "monti-release-"));
try {
	for (const { dir, folder, pkg } of packages) {
		const before = new Set(readdirSync(work));
		execFileSync("pnpm", ["pack", "--pack-destination", work], { cwd: dir, stdio: "inherit" });
		const tarball = readdirSync(work).find((file) => !before.has(file) && file.endsWith(".tgz"));
		if (!tarball) throw new Error(`${pkg.name}: pnpm pack produced no tarball`);
		const unpacked = path.join(work, folder);
		mkdirSync(unpacked);
		execFileSync("tar", ["-xzf", path.join(work, tarball), "-C", unpacked]);
		// The bundle is unpacked under `package/`.
		renameSync(path.join(unpacked, "package"), path.join(out, folder));
		// The license lives once at the repo root. Copy it into every bundle.
		copyFileSync(path.join(root, "LICENSE"), path.join(out, folder, "LICENSE"));
		console.log(`${pkg.name}@${version} → ${folder}/`);
	}
} finally {
	rmSync(work, { recursive: true, force: true });
}

copyFileSync(path.join(root, "LICENSE"), path.join(out, "LICENSE"));

const rows = packages.map(
	({ folder, pkg }) =>
		`| \`${pkg.name}\` | \`"${pkg.name}": "github:monti-cms/monti#release/v${version}&path:/${folder}"\` |`,
);
writeFileSync(
	path.join(out, "README.md"),
	`# Monti release bundle v${version}

This branch is generated by the release workflow. Do not edit it by hand. The source is on the \`main\` branch.

Install with pnpm (\`path:\` is supported by pnpm only).

| Package | package.json |
| --- | --- |
${rows.join("\n")}
`,
);
